services:
  flask:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    # dodanie wolumenu
    volumes:
      - ./api:/app
    image: api:v1
    container_name: api
    depends_on:
    - database
    networks:
    - backend
  
  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    ports: 
      - 8883:8883
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./broker/pwfile:/mosquitto/config/pwfile
    image: broker:v1
    container_name: broker
    networks:
    - backend
  
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: database:v1
    container_name: postgres
    networks:
    - backend

networks:
  backend:
    driver: bridge

  # ingestor:
  #   build:
  #     context: ./ingestor
  #     dockerfile: Dockerfile
  #   ports:
  #     - 1883:1883
  #   image: ingestor:v1
  #   container_name: ingestor
